### PR TITLE
Upgrade extension to Jupyter 3_X

### PR DESCRIPTION
**Pull request by WestedCrean**
Upgraded theme according to https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html

Tested on Python 3.9.1 with JupyterLab 3.0.12

### CODE REVIEW

**Comment by shahinrostami** [comment]
Hi - thanks for this Pull request. I've updated for Jupyter Lab 3 support.

**Comment by dkinneyBU** [comment]
@WestedCrean @shahinrostami  Doesn't appear to be working with 3.0.16? I followed the install instructions, it appears in the Extensions tab, but the theme is not listed under Settings > Jupyter Lab Theme (just Light and Dark). I rebuilt lab again just to be sure, still not appearing.

I'm happy to downgrade to .12 if that will "fix" it...

**Comment by shahinrostami** [comment]
@dkinneyBU  I've tested it with `3.1.4` (see screenshot below). I'll update and see if there's any helpful error message to start from.

Screenshot 2021-08-23 at 20 49 05

**Comment by shahinrostami** [comment]
@dkinneyBU well, it took me to `3.1.17` and seemed to work 

Screenshot 2021-08-23 at 20 53 02

Have you checked to see if it's installing the correct version of `theme-purple-please`? See below with `jupyter labextension list`

Screenshot 2021-08-23 at 20 57 36

**Comment by shahinrostami** [comment]
@dkinneyBU p.s. I have just noticed this comment thread is on the pull request, FYI @dkinneyBU I have updated the actual theme so it's on `npm` and can be installed through the normal method for jupyterlab.

**Pull request closed without merging**
